# Generated by Django 2.2.6 on 2019-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('full_desc', models.TextField()),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
